version: '3'
services:
  db:
    image: mysql:5.6.50
    command: mysqld --character-set-server=utf8
    environment:
      MYSQL_DATABASE: study_repo_app_development
      MYSQL_ROOT_PASSWORD: <%= ENV['MYSQL_PASSWORD'] %>
      MYSQL_USER: <%= ENV['MYSQL_USER'] %>
    ports:
      - "4306:3306"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/myproject
    environment:
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
